name: first-work-flow

on:
  push:
    branches:
      - "main"  # Space after dash, plural 'branches'

jobs:           # Plural 'jobs'
  first-work-flow:
    name: first-work-flow-job
    runs-on: ubuntu-latest
    steps:
      - name: runs bash commands
        run: echo "first workflow" # Aligned with 'name'
        shell: bash                # Aligned with 'name'
